# TCL File Generated by Component Editor 13.0
# Wed Apr 16 14:51:09 CEST 2014
# DO NOT MODIFY


# 
# ime_avalon_seg7p "7-Seg Display" v13.0
# M. Pichler 2014.04.16.14:51:09
# Seven Segment Display
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module ime_avalon_seg7p
# 
set_module_property DESCRIPTION "Seven Segment Display"
set_module_property NAME ime_avalon_seg7p
set_module_property VERSION 13.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DE2_35
set_module_property AUTHOR "M. Pichler"
set_module_property DISPLAY_NAME "N x 7-Seg Display"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL ime_avalon_seg7
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ime_avalon_seg7.vhd VHDL PATH hdl/ime_avalon_seg7.vhd TOP_LEVEL_FILE
add_fileset_file seg7_lut.vhd VHDL PATH hdl/seg7_lut.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL ime_avalon_seg7
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ime_avalon_seg7.vhd VHDL PATH hdl/ime_avalon_seg7.vhd
add_fileset_file seg7_lut.vhd VHDL PATH hdl/seg7_lut.vhd


# 
# parameters
# 
add_parameter G_DIGITS INTEGER 8
set_parameter_property G_DIGITS DEFAULT_VALUE 8
set_parameter_property G_DIGITS DISPLAY_NAME G_DIGITS
set_parameter_property G_DIGITS TYPE INTEGER
set_parameter_property G_DIGITS UNITS None
set_parameter_property G_DIGITS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset_n reset_n Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clock
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_write write Input 1
add_interface_port s1 avs_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit SVD_ADDRESS_GROUP ""

add_interface_port conduit coe_hex export Output g_digits*7

