# TCL File Generated by Component Editor 13.0
# Wed May 14 13:15:40 CEST 2014
# DO NOT MODIFY


# 
# leading_zero_detection "Leading Zero Detector" v13.0
# M. Pichler 2014.05.14.13:15:40
# Leading Zero Detector
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module leading_zero_detection
# 
set_module_property DESCRIPTION "Leading Zero Detector"
set_module_property NAME leading_zero_detection
set_module_property VERSION 13.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "CI Modules"
set_module_property AUTHOR "M. Pichler"
set_module_property DISPLAY_NAME "Leading Zero Detector"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL leading_zero_detector
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file leading_zero_detector.vhd VHDL PATH hdl/leading_zero_detector.vhd TOP_LEVEL_FILE

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL leading_zero_detector
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file leading_zero_detector.vhd VHDL PATH hdl/leading_zero_detector.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point cis1
# 
add_interface cis1 nios_custom_instruction end
set_interface_property cis1 clockCycle 0
set_interface_property cis1 operands 1
set_interface_property cis1 ENABLED true
set_interface_property cis1 EXPORT_OF ""
set_interface_property cis1 PORT_NAME_MAP ""
set_interface_property cis1 SVD_ADDRESS_GROUP ""

add_interface_port cis1 dataa dataa Input 32
add_interface_port cis1 result result Output 32

